# Internship Session 11/1: numpy arrays refresher
![sea turtle!](https://kids.nationalgeographic.com/content/dam/kids/photos/animals/Reptiles/A-G/green-sea-turtle-closeup-underwater.adapt.945.1.jpg)

### Exercises 1 & 2
1. In the array below, how can you select the element '222'? What command is required? What about the element '11'
2. In the array below, how can you select the second row? What about the third column? (Assume that the first row means index 0, and so on)

In [32]:
import numpy as np
a = np.array([[1, 2, 10, 11], [2, 3, 7, 9], [222, 1,3, 14], [100, 101, 223, 17]])
print(a)
#a[#what goes here?]

[[  1   2  10  11]
 [  2   3   7   9]
 [222   1   3  14]
 [100 101 223  17]]


### Exercise 3
3. In the array below, how can you select the element '19'? What about the element '28'?

In [27]:
b = np.arange(32).reshape(4,2,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

### Challenges
In the array below, how can you select the first row in the second group? What about all elements in the first group? What about all elements in the second column?

In [33]:
b = np.arange(32).reshape(4,2,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

### More challenges
How many dimensions does the array below have? What is its shape?
How would you select the upper-right-corner element? What about the lower-left-corner element?

In [47]:
d = np.random.rand(2, 2, 3, 4)
d

array([[[[0.0563151 , 0.27249155, 0.89855616, 0.11473664],
         [0.68748616, 0.55274386, 0.96177529, 0.60566423],
         [0.24251094, 0.25865669, 0.77526765, 0.44701775]],

        [[0.28401711, 0.93898669, 0.62191578, 0.70930346],
         [0.25098372, 0.30152189, 0.85615966, 0.8744525 ],
         [0.97344181, 0.15263011, 0.99784537, 0.87525214]]],


       [[[0.90000432, 0.25860898, 0.33950206, 0.46402271],
         [0.78590954, 0.72957533, 0.89594684, 0.06424857],
         [0.63727182, 0.75206629, 0.78578794, 0.16578737]],

        [[0.80873221, 0.71898517, 0.19643637, 0.44136108],
         [0.83745689, 0.67791866, 0.16954483, 0.9692419 ],
         [0.54316454, 0.38004336, 0.81685491, 0.95207931]]]])