# Here are some visuals to help you understand numpy arrays better

### And, as per usual, a picture of a cute sea animal.
![manatee](https://i.huffpost.com/gen/1272530/thumbs/o-MANATEES-900.jpg?5)

### We'll first create a 4x5 array. 

In [1]:
import numpy as np
a = np.arange(1,60,3).reshape(4,5)

Our array, a, looks like this:

`a = array([[ 1,  4,  7, 10, 13],
       [16, 19, 22, 25, 28],
       [31, 34, 37, 40, 43],
       [46, 49, 52, 55, 58]])` 

![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/Screen%20Shot%202018-11-02%20at%205.23.03%20PM.png?token=AmUbDpWjSe4asRuC415N-d381PDnMuTAks5b7ahPwA%3D%3D)


Now, what if we want to select a part of this array? For example, we want to select the element '25'? 

In [2]:
a[1,3]

25

It can help to think of your selection as an intersection of indices.

![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/Screen%20Shot%202018-11-02%20at%205.40.45%20PM.png?token=AmUbDh80CPWOXWsxehydto2v0jYHJcWGks5b7ah5wA%3D%3D)

Now, let's try selecting just the first row.

In [3]:
a[0,:]

array([ 1,  4,  7, 10, 13])

![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/firstrow.png?token=AmUbDqPS-gD5MuRbGX9qog99B0RbkvFMks5b7aiNwA%3D%3D)

What if we want to select the fifth column? 

In [5]:
a[:,4]

array([13, 28, 43, 58])

![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/lastcolumn.png?token=AmUbDsXOpKqJbn9QlEKgnIcbXtXsaoUAks5b7aibwA%3D%3D)

Now, what if we want to select part of a column or row? Here is where the colon notation gets tricky.

I want to return the elements '22' and '37', in their own array. Using colon notation can return a range of values. 

However, Python uses what we call an "uninclusive" range. The last number in any user-specified range is not included, by default.

For example, using the "range" function, such as `range(0, 10)`, returns the numbers 0 through 9. 

In [15]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


How do we select '22' and '37'? What is the intersection we're looking for?

In [16]:
a[1,2:5]

array([22, 25, 28])

![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/partofcolumn.png?token=AmUbDuIihl2TPdYe2k_HE-ytjShglXQ3ks5b7aiswA%3D%3D)

## What about 3D arrays?
### We'll first create a 2x2x5 array.

In [20]:
a = np.arange(1,60,3).reshape(2,2,5)

`a = array([[[ 1,  4,  7, 10, 13],
        [16, 19, 22, 25, 28]],`

       [[31, 34, 37, 40, 43],
        [46, 49, 52, 55, 58]]])
        
Graphically, it looks like this. 
![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/Screen%20Shot%202018-11-02%20at%206.14.07%20PM.png?token=AmUbDrtNU8p2FFYj4UNlh7hBvBuiEt0bks5b7ajGwA%3D%3D)
The array has 2 groups, which each have two rows and 5 columns.

Suppose we want to select the values 31 and 46. What is the intersection that produces these values?

In [22]:
a[1,:,0]

array([31, 46])

![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/Screen%20Shot%202018-11-02%20at%206.21.08%20PM.png?token=AmUbDmk8JrWSOYRqc2SlBxQsn7RpJKkxks5b7ajbwA%3D%3D)

## Some more challenges

In [24]:
c = np.arange(1,72,3).reshape(2,3,4)
c

array([[[ 1,  4,  7, 10],
        [13, 16, 19, 22],
        [25, 28, 31, 34]],

       [[37, 40, 43, 46],
        [49, 52, 55, 58],
        [61, 64, 67, 70]]])

In table form, this array looks like this: 
![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/Screen%20Shot%202018-11-07%20at%2011.28.01%20AM.png?token=AmUbDkvrUr9WOl3dMf3WN4OD_tu96Yeiks5b7ajvwA%3D%3D)

1. What code can you write to return the value '49'?
2. What code can you write to return the third row in the first group?
3. What code can you write to return the values '55' and '58'?

If you're stuck, think about the intersections required to find each one of these values! What combination of rows, columns and groups are necessary?

In [25]:
c[1,1,0]

49

In [26]:
c[0,2,:]

array([25, 28, 31, 34])

In [27]:
c[1,1,2:4]

array([55, 58])